included:
  - Sources
  - Tests
  - Frameworks/Open/Sources
  - Frameworks/Open/Tests
excluded:
  - Configurations
  - Pods
  - Resources
  - build
  - Support
disabled_rules:
  - trailing_whitespace
  - nesting
  - cyclomatic_complexity
  - file_length
