os:
- osx
language: generic
osx_image: xcode9
cache:
  directories:
  - Carthage
  - Pods
install:
  - brew upgrade swiftlint
  - brew outdated carthage || brew upgrade carthage
  - bundle install
  - bundle exec pod install
  - carthage update --cache-builds
script:
  - bundle exec rake ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
